import { useState, type ReactNode } from 'react';
import { Activity, ArrowDown, ArrowUp, Car, Check, ChevronLeft, ChevronRight, Cpu, Database, Focus, Gauge, Layers3, MapPin, Minus, Plus, Radio, Search, Server, ShieldCheck, Signal, Wifi, X, ZoomIn, type LucideIcon } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Chart, type ChartKind } from './Chart';
import { downloadCsv, ExportButton, usePlatform } from './Shell';
import { type Row } from './data';
import city from '@/assets/connected-city.jpg';
import { toast } from 'sonner';
export function Panel({title,children,action,className=''}:{title:string;children:ReactNode;action?:ReactNode;className?:string}) {return <section className={`glass-panel ${className}`}><div className="panel-heading"><h3>{title}</h3>{action}</div>{children}</section>;}
type Stat = {label:string;value:string;unit:string;change:string;icon:LucideIcon;tone:string;down?:boolean};
export function Stats({items,four=false}:{items:Stat[];four?:boolean}) {
  const {region,period,date} = usePlatform();
  return <div className={`stats-grid ${four?'four':''}`}>{items.map(({label,value,unit,change,icon:Icon,tone,down})=>{
    let display = value;
    if (region!=='上海市全域' && !['%','分','ms','km/h'].includes(unit)) { const n=Number(value.replaceAll(',',''))*.24;display=n>=1000?Math.round(n).toLocaleString('en-US'):n>=100?n.toFixed(0):n.toFixed(1); }
    if (period!=='日' && ['万km','MWh','吨'].includes(unit)) {display=(Number(display.replaceAll(',',''))*(period==='周'?7:30)).toLocaleString('en-US',{maximumFractionDigits:1});}
    if (date!=='2026-10-09' && !['%','分','ms','km/h'].includes(unit)) {display=(Number(display.replaceAll(',',''))*.93).toLocaleString('en-US',{maximumFractionDigits:1});}
    return <section className="stat-card glass-panel" data-tone={tone} key={label}><div className="stat-head">{label}<Icon className="stat-icon"/></div><div className="stat-number">{display}<small>{unit}</small></div><div className="stat-bottom">较上{period==='日'?'日':period==='周'?'周':'月'}<b>{down?<ArrowDown/>:<ArrowUp/>}{change}</b><span>{down?'持续优化':'稳步增长'}</span></div></section>;
  })}</div>;
}
export function ChartPanel({title,kind,labels,names,data,size='',tabs=false,note}:{title:string;kind:ChartKind;labels?:string[];names?:string[];data?:number[][];size?:string;tabs?:boolean;note?:string}) {
  const {period,region,date,revision} = usePlatform();
  const [localPeriod,setLocalPeriod]=useState<string|null>(null);
  return <Panel title={title} action={tabs?<div className="segmented">{['日','周','月'].map(p=><Button variant="ghost" aria-pressed={(localPeriod??period)===p} onClick={()=>setLocalPeriod(p)} key={p}>{p}</Button>)}</div>:<small>{kind==='donut'?'车辆类型分布':kind==='radar'?'多维能力评估':'实时统计'}</small>}><Chart key={`${region}-${date}-${revision}`} kind={kind} labels={labels} names={names} data={data} size={size} period={localPeriod??period}/>{note&&<div className="chart-note"><Activity/>{note}</div>}</Panel>;
}
export function CityMap({large=false}:{large?:boolean}) {
  const {region}=usePlatform();
  const [zoom,setZoom]=useState(1);
  const [layer,setLayer]=useState(true);
  const [selection,setSelection]=useState<string|null>(null);
  return <Panel title="车路协同 · 全域实时态势" className={`city-panel ${large?'big-map':''}`} action={<div className="flex items-center gap-2 text-success text-[10px]"><span className="live-dot"/>LIVE <span className="text-muted-foreground">实时感知</span></div>}><div className="city-visual"><img src={city} width={1920} height={1024} alt="上海智慧城市车路协同数字孪生视图" style={{transform:`scale(${zoom})`,transition:'transform .4s'}}/><div className="map-toolbar"><MapPin size={12}/>{region} <span className="text-muted-foreground">/ 数字孪生视图</span></div><div className="map-tools"><Button size="icon" variant="ghost" title="放大地图" aria-label="放大地图" onClick={()=>setZoom(Math.min(zoom+.15,1.75))}><Plus/></Button><Button size="icon" variant="ghost" title="缩小地图" aria-label="缩小地图" onClick={()=>setZoom(Math.max(zoom-.15,1))}><Minus/></Button><Button size="icon" variant="ghost" title="重置视图" aria-label="重置视图" onClick={()=>setZoom(1)}><Focus/></Button><Button size="icon" variant="ghost" title="切换感知图层" aria-label="切换感知图层" aria-pressed={layer} onClick={()=>setLayer(!layer)}><Layers3/></Button></div>{layer&&<><Button variant="ghost" className="map-point point-one" onClick={()=>setSelection('浦东智慧公交枢纽')}><Car/>智慧公交 · 128 辆</Button><Button variant="ghost" className="map-point point-two" onClick={()=>setSelection('世纪大道路侧单元')}><Radio/>RSU · 在线 86 台</Button><Button variant="ghost" className="map-point point-three" onClick={()=>setSelection('陆家嘴车路协同示范区')}><Signal/>车路协同示范区</Button><Button variant="ghost" className="map-point point-four" onClick={()=>setSelection('城市物流运输车队')}><Car/>物流车队 · 236 辆</Button><div className="map-ring"/></>}<div className="map-bottom"><div className="map-legend"><span><i className="legend-dot"/>网联车辆</span><span><i className="legend-dot bus"/>智慧公交</span><span><i className="legend-dot rsu"/>路侧设备</span></div><span>31.2304° N · 121.4737° E</span></div></div><div className="city-summary"><div><Car/>在线车辆 <strong>24,892</strong></div><div><Radio/>协同路口 <strong>328</strong></div><div><Wifi/>网络覆盖 <strong>99.8%</strong></div><div><Gauge/>平均速度 <strong>42.6</strong><span>km/h</span></div></div>{selection&&<div className="modal-overlay" onClick={()=>setSelection(null)}><div className="detail-modal" role="dialog" aria-modal="true" aria-label="感知节点详情" onClick={e=>e.stopPropagation()}><div className="modal-title"><h3>{selection}</h3><Button variant="ghost" size="icon" aria-label="关闭" onClick={()=>setSelection(null)}><X/></Button></div><div className="detail-grid"><div><small>连接状态</small><span className="status-pill">正常在线</span></div><div><small>覆盖区域</small><b>{region}</b></div><div><small>通信延迟</small><b>12 ms</b></div><div><small>最近同步</small><b>2026-10-09 15:19:00</b></div></div><div className="modal-foot"><Button onClick={()=>setSelection(null)}>确认</Button></div></div></div>}</Panel>;
}
export function HealthPanel() {return <Panel title="平台运行状态" action={<small>系统健康监测</small>}><div className="health-content"><div className="health-score"><div className="score-ring"><div><b>98.6</b><small>健康评分</small></div></div><div><h4>运行状态良好</h4><p>所有核心服务稳定运行</p><p className="mt-2 text-success">↑ 较昨日提升 1.2 分</p></div></div>{[{icon:Server,label:'云端服务',status:'运行正常'},{icon:Database,label:'数据接入',status:'连接正常'},{icon:ShieldCheck,label:'安全防护',status:'防护中'},{icon:Signal,label:'通信网络',status:'信号优良'}].map(({icon:Icon,label,status})=><div className="health-row" key={label}><span><Icon/>{label}</span><small><span className="live-dot"/>{status}</small></div>)}<div className="resource-bars"><div><label>CPU 使用率 <b>32%</b></label><div className="progress-track"><span className="w-[32%]"/></div></div><div><label>内存使用率 <b>58%</b></label><div className="progress-track green"><span className="w-[58%]"/></div></div></div></div></Panel>;}
const statusClass = (status:string) => ['待处理','待检修','离线','高风险'].includes(status)?'danger':['处理中','待升级','缓行','中风险'].includes(status)?'warn':['停泊中','低风险'].includes(status)?'blue':'';
export function Status({value}:{value:string}) {return <span className={`status-pill ${statusClass(value)}`}>{value}</span>;}
export function DataTable({title,headers,rows,pageSize=5,kind='vehicle'}:{title:string;headers:string[];rows:Row[];pageSize?:number;kind?:string}) {
  const {region,date}=usePlatform();
  const [query,setQuery]=useState('');const [status,setStatus]=useState('全部状态');const [page,setPage]=useState(1);const [detail,setDetail]=useState<Row|null>(null);const [resolved,setResolved]=useState<string[]>([]);
  const statuses=Array.from(new Set(rows.map(row=>row.status)));
  const filtered=rows.map(row=>resolved.includes(row.id)?{...row,status:'已处理'}:row).filter(row=>(region==='上海市全域'||row.region===region)&&(status==='全部状态'||row.status===status)&&(`${row.id} ${row.fields.join(' ')} ${row.status}`).toLowerCase().includes(query.toLowerCase()));
  const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize));const currentPage=Math.min(page,totalPages);const visible=filtered.slice((currentPage-1)*pageSize,currentPage*pageSize);
  const resolve=()=>{if(!detail)return;setResolved([...resolved,detail.id]);setDetail(null);toast.success('事件已处理',{description:'处置结果已更新到演示列表'});};
  return <Panel title={title} action={<div className="table-toolbar"><label className="search-input"><Search/><input aria-label={`搜索${title}`} placeholder={kind==='vehicle'?'搜索车牌 / 车辆类型':'搜索编号 / 关键词'} value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label><select className="filter-select h-7 text-[10px]" aria-label={`${title}状态筛选`} value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option>全部状态</option>{statuses.map(item=><option key={item}>{item}</option>)}</select><ExportButton onClick={()=>downloadCsv(title,[...headers,'状态'],filtered.map(row=>[...row.fields,row.status]))}/></div>}><div className="table-scroll"><table className="data-table"><thead><tr>{headers.map(header=><th key={header}>{header}</th>)}<th>状态</th><th>操作</th></tr></thead><tbody>{visible.map(row=><tr key={row.id}>{row.fields.map((field,i)=><td key={i}>{field.includes('风险')?<Status value={field}/>:field.startsWith('2026-')?field.replace('2026-10-09',date):field}</td>)}<td><Status value={row.status}/></td><td><Button variant="link" onClick={()=>setDetail(row)}>查看详情 <ChevronRight size={11}/></Button></td></tr>)}</tbody></table>{!visible.length&&<div className="empty-state">暂无匹配的数据</div>}</div><div className="table-footer"><span>共 {filtered.length} 条记录 · 显示 {visible.length?(currentPage-1)*pageSize+1:0}–{Math.min(currentPage*pageSize,filtered.length)} 条</span><div className="pagination"><Button variant="ghost" size="icon" aria-label="上一页" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}><ChevronLeft/></Button>{Array.from({length:Math.min(totalPages,4)},(_,i)=>i+1).map(p=><Button key={p} variant={p===currentPage?'default':'ghost'} aria-label={`第${p}页`} onClick={()=>setPage(p)}>{p}</Button>)}{totalPages>4&&<span>… {totalPages}</span>}<Button variant="ghost" size="icon" aria-label="下一页" disabled={currentPage===totalPages} onClick={()=>setPage(currentPage+1)}><ChevronRight/></Button><span>{pageSize} 条/页</span></div></div>{detail&&<div className="modal-overlay" onClick={()=>setDetail(null)}><section className="detail-modal" role="dialog" aria-modal="true" aria-label="记录详情" onClick={e=>e.stopPropagation()}><div className="modal-title"><h3>{kind==='event'?'预警事件详情':kind==='device'?'设备详情':kind==='road'?'路段运行详情':'车辆运行详情'}</h3><Button variant="ghost" size="icon" aria-label="关闭" onClick={()=>setDetail(null)}><X/></Button></div><div className="detail-grid">{headers.map((header,i)=><div key={header}><small>{header}</small><b>{detail.fields[i]}</b></div>)}<div><small>当前状态</small><Status value={detail.status}/></div><div><small>记录编号</small><b>{detail.id}</b></div></div><div className="modal-foot"><Button variant="outline" onClick={()=>setDetail(null)}>关闭</Button>{kind==='event'&&detail.status!=='已处理'&&<Button onClick={resolve}><Check/>标记已处理</Button>}</div></section></div>}</Panel>;
}
export const vehicleHeaders=['车牌号码','车辆类型','所在区域','实时车速','电池电量','健康评分'];
export const eventHeaders=['事件编号','预警类型','关联对象','发生区域','发生时间','风险等级'];
